# Generated by Django 5.2.8 on 2025-12-09 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
