"""
Django settings for miniecommerce project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--hn&-m)n9y3cvfcc-wq35k&-u4v30l03=wdr&mng#xhuozpcq&'

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'miniecommerce-hb7o.onrender.com']
DEBUG = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'mpesapayment',
    'cloudinary',
    'widget_tweaks',
    'accounts.apps.AccountsConfig',
    'helpcentre',
    
    
]


from decouple import config
# register our custom user model 
AUTH_USER_MODEL = 'accounts.CustomUser'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
WHATSAPP_SUPPORT_NUMBER = config('WHATSAPP_SUPPORT_NUMBER')
# Email backend for password reset (development)
# EMAIL_BACKEND = 'django.store.mail.backends.console.EmailBackend'
# Register Login URL 
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'store:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

import cloudinary
from decouple import config
CLOUDINARY_CONFIGS = {
    'cloud_name' : config('CLOUDINARY_CLOUD_NAME'),
    'api_key' : config('CLOUDINARY_API_KEY'),
    'api_secret' : config('CLOUDINARY_API_SECRET'),
}
if CLOUDINARY_CONFIGS['cloud_name']:
    cloudinary.config(**CLOUDINARY_CONFIGS)

import os
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'miniecommerce-hb7o.onrender.com']

# Add ngrok dynamically if set
NGROK_URL = config('NGROK_URL', default='')
if NGROK_URL:
    from urllib.parse import urlparse
    host = urlparse(NGROK_URL).netloc  # extract host from URL
    ALLOWED_HOSTS.append(host)
MPESA_CONSUMER_KEY = config("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET = config("MPESA_CONSUMER_SECRET")
MPESA_SHORTCODE = config("MPESA_SHORTCODE")
MPESA_PASSKEY = config("MPESA_PASSKEY")
MPESA_BASE_URL = config("MPESA_BASE_URL", default="https://sandbox.safaricom.co.ke")
MPESA_CALLBACK_URL = config("MPESA_CALLBACK_URL")

# Optional: debug prints
print("M-Pesa Base URL:", MPESA_BASE_URL)
print("M-Pesa Callback URL:", MPESA_CALLBACK_URL)






MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'miniecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


WSGI_APPLICATION = 'miniecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "minicommerce/static",
]

# Optional for deployment
STATIC_ROOT = BASE_DIR / "staticfiles"




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Allow secure proxy headers (required for Render HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Optional: only if using forms
CSRF_TRUSTED_ORIGINS = ['https://miniecommerce-hb7o.onrender.com']