# Generated by Django 5.2.8 on 2025-12-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesapayment', '0001_initial'),
        ('store', '0003_alter_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='Unique CheckoutRequestID from M-Pesa STK Push', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='store.order'),
        ),
    ]
